# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loyali', '0001_initial'),
        ('loyaliapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='loyaliapi.MobileUser'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='loyali.VendorUser'),
        ),
        migrations.AddField(
            model_name='rewards',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyaliapi.MobileUser'),
        ),
        migrations.AddField(
            model_name='rewards',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyali.Vendor'),
        ),
        migrations.AddField(
            model_name='cardsinuse',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyali.Card'),
        ),
        migrations.AddField(
            model_name='cardsinuse',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyaliapi.MobileUser'),
        ),
        migrations.AddField(
            model_name='card',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='loyali.Vendor'),
        ),
    ]
