# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-10 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyaliapi', '0001_initial'),
        ('loyali', '0002_auto_20170103_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyaliapi.MobileUser')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyali.Vendor')),
            ],
        ),
    ]
