# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-10 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyali', '0004_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
